### ISSUE TITLE
avoid breaking compatibility

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-grigoriefflab#7]
https://github.com/scipion-em/scipion-em-grigoriefflab/commit/d05104fefefc40268cd4bfa3411eccf1cc774e64
breaks backwards compatibility....do the casting when using the param.

**Comment by delarosatrevin** [comment]
@pconesa is this issue still relevant?

**Comment by pconesa** [comment]
It's relevant, but it is fixed.
