### ISSUE TITLE
deprecate ctffind3

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-grigoriefflab#8]
It's been 5 years already. I don't see the reason to use it anymore...
I would also limit the number of supported ctffind4 versions to a couple, current protocol code is overcomplicated because of this..

**Comment by delarosatrevin** [comment]
Completely agree, good moment to clean up the code.

**Comment by josuegbl** [comment]
Yeah! I think nobody uses ctffind3 nowadays.

**Comment by delarosatrevin** [comment]
Some steps were made in https://github.com/scipion-em/scipion-em-grigoriefflab/pull/11, but more work is required.

**Comment by azazellochg** [comment]
considering a new repo for ctffind, this is not relevant anymore.
